#!/bin/bash

set -e

docker-compose down
docker-compose up -d --build
./scripts/wait_for_syslog_client
docker-compose exec -T syslog_client wget localhost:5000
docker-compose logs syslog_server | grep OK
echo $?
